### ISSUE TITLE
Disable item by default in items.json

### ISSUE THREAD

**Issue by Muparadzi** [namidaka/crpg#370]
Items.json should have a 'disabled' field which we can set during an item export. Bannerlord item XMLs cannot have custom fields, so this must be configured via the item id.

Example: 
- `crpg_sword_h0` should be treated as normal
- `crpgdisabled_sword_h0` should be disabled by default

**Comment by or2e** [comment]
[I think I've implemented it here](https://github.com/namidaka/crpg/pull/349/commits/9299c8e66f35688d760ffab8eea29574a63d17ad#diff-d53f846e0f1388c207b03c1a306bcc173938b30e669e78f8a0c37e2fca25eec4R2222)
