### ISSUE TITLE
Activity logs for clan

### ISSUE THREAD

**Issue by namidaka** [namidaka/crpg#45]
From crpg created by [verdie-g](https://github.com/verdie-g): verdie-g/crpg#706  

- [x] clan create
- [x] clan delete
- [x] clan member role edit
- [x] clan member added
- [x] clan member kicked

**Comment by or2e** [comment]
https://github.com/namidaka/crpg/pull/374

**Comment by or2e** [comment]
https://github.com/crpg2/crpg/pull/515
